const { text } = require("express");
const mongoose=require("mongoose");

//autoIncrement = require('mongoose-auto-increment');

//create schema  for service that is generated by the department 

const ServiceSchema= new mongoose.Schema(
{
    Name:{type:String,required:true,unique:true},
    price:{type:Number,required:true},
    id:false

})

//create schema for medicine collection
const DepartmentSchema=new mongoose.Schema(

{
_id:{type:Number},
Name:{type:String,required:true,unique:true},
Service:{ServiceSchema,type:Array,required:false},
doctor:{type:mongoose.Schema.Types.ObjectId,ref:"Doctor"},
patient:{type:mongoose.Schema.Types.ObjectId,ref:'patient'},
//phoneNumber:{type:Number,required:true,unique:true}
})


//DepartmentSchema.plugin(autoIncrement.plugin, 'Department');
//mapping schema bind collection  -- modeling
 mongoose.model("Department",DepartmentSchema);