

const { text } = require("express");
const mongoose=require("mongoose");
//autoIncrement = require('mongoose-auto-increment');

//create schema  for service that is generated by the department 
const ServiceSchema= new mongoose.Schema(
{
    _id:Number,
    name:{type:String,required:true,unique:true},
    price:{type:Number,required:true},
   departmentID:{type:Number,required:true,ref:"Department"}
}
)

//DepartmentSchema.plugin(autoIncrement.plugin, 'Department');
//mapping schema bind collection  -- modeling
 mongoose.model("Service",ServiceSchema);